version: '3.8'

services:
  express:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "sql1"
    links:
      - "sql1"

  sql1:
    image: mysql:latest
    container_name: "sql1_new"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=productos
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: